CREATE DATABASE PruebaProjecto;
USE PruebaProjecto
GO
CREATE TABLE TIPOS_MUSICA
( ID_TIPO INT,
NOMBRE_TIPO VARCHAR(20) NOT NULL,
CONSTRAINT UN_NOMBRE_TIPO UNIQUE (NOMBRE_TIPO),
CONSTRAINT PK_TIPOS_MUSICA PRIMARY KEY (ID_TIPO) );
GO